### Locations backend configuration file example
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v0/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/web-api-skeleton.log
      archivedLogFilenamePattern: logs/web-api-skeleton-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

locations:
  uhdsUrl: http://example.com/path-to-json-file.json
  icalUrl: https://www.google.com/calendar/ical/calendar-id%40group.calendar.google.com/public/basic.ics
  diningJsonOut: change-me.json
  cacheDirectory: cache
  campusMapHttpData: https://example.com/locations.json
  campusmapJsonOut: campusmap.json
  extensionUrl: http://example.com/extension_locations.xml
  extensionXmlOut: extension-locations.xml
  apiEndpointUrl: https://api.example.com/v1/
  arcGisQueryUrl: http://arcgis.example.com/
  arcGisJsonOut: arcgis.json
  libraryUrl: https://api.library.com/v1/
  buildingGeometries: buildings/converted-coordinates.json
  parkingGeometries: parking/converted-coordinates.json

httpClientConfiguration:
  timeout: 150ms
  connectionTimeout: 150ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 2
  maxConnectionsPerRoute: 2
  keepAlive: 0ms
  retries: 0
  userAgent: api-client

api:
  endpointUri: https://api.example.com/v1/
