server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

dataSources:
  dataSources: ['awsEs']
  awsEs:
    domain: yourEsDomain.region.es.amazonaws.com
    region: 'us-east-2'
    accessKeyId: top
    secretAccessKey: secret
